- tokens/MEX-455c57/info.json
- tokens/USDC-c76f1f/info.json
- tokens/WEGLD-bd4d79/info.json
Added the ledger signature field for 2 tokens.
They will be used for displaying a custom flow when transferring them via Ledger Nano device
> added ledger signatures for 2 tokens

- tokens/MEX-455c57/info.json
update MEX's ledger signature as the previous signature included malformed input data
> Update mex ledger signature

- tokens/FIVE-d8b982/info.json
> update social networks

- tokens/EARTH-cac0a1/info.json
trying to fix this EARTH json info
> Fix EARTH json

- tokens/OXSY-3dc78b/info.json
> Updated oxsy website

- tokens/HETO-663cf8/info.json
> Update and rename Info.json to info.json

- tokens/ITHEUM-df6f26/info.json
- tokens/UTK-2f80e9/info.json
generated and added ledger signatures for ITHEUM and UTK
> added ledger signatures for itheum and utk

- accounts/erd16jruked88jgtsar78ej85hjp3qsd9jkjcw4swsn7k0teqh3wgcqqgyrupq.json
> add 2nd coinbase account

- accounts/erd1qqqqqqqqqqqqqpgqawujux7w60sjhm8xdx3n0ed8v9h7kpqu2jpsecw6ek.json
Signed-off-by: Claudiu Lataretu <claudiu.lataretu@gmail.com>
> LKASH locking contract branding

- accounts/erd1qqqqqqqqqqqqqpgqeh4yv09rmyg4xgn5ma03mvm4v5gndu8w2jpsglz3cn.json
Labels for the newly deployed Escrow contract
> escrow contract label

- accounts/erd1qqqqqqqqqqqqqpgq2srxelqexsxkg82rr8ygwsq684faa2syu7zs4qa7tx.json
- accounts/erd1qqqqqqqqqqqqqpgqs8zrk6uq5z6r5lm07cvmtuw2hxm4d8uru7zszqp8vx.json
> two new SCs

- accounts/erd1qqqqqqqqqqqqqpgqglgkaxm73j7mhw5u940fsmmncnayxj884fvs54lnr6.json
Hi team,
We have launched the aggregator contract: [erd1qqqqqqqqqqqqqpgqglgkaxm73j7mhw5u940fsmmncnayxj884fvs54lnr6](https://explorer.multiversx.com/accounts/erd1qqqqqqqqqqqqqpgqglgkaxm73j7mhw5u940fsmmncnayxj884fvs54lnr6)
> Add AshSwap aggregator contract

- accounts/erd1qqqqqqqqqqqqqpgqp70a5f00udh4d047lzdcdajv4pqznknassnsunpy0r.json
liquid stake locking contract branding
> liquid stake locking contract

- accounts/erd1qqqqqqqqqqqqqpgqaf8fzwmas77xxr7qwnxd6j3qsctv55e74fvsmvq675.json
- accounts/erd1qqqqqqqqqqqqqpgqfa28799n3yt5lrzt75lgvqfz4jxsf2ef4fvs7rkgzy.json
- accounts/erd1qqqqqqqqqqqqqpgqhvj3vgwhzg26ghaseae6ehleq0r73xd24fvs358shm.json
- accounts/erd1qqqqqqqqqqqqqpgqlxrx76w63v6zp4gh0rpexe7hhjnz63244fvs6xzgrd.json
- accounts/erd1qqqqqqqqqqqqqpgqvdkft2eq9zh7cu9tkxartshu764tqe7s4fvsaw99xj.json
- accounts/erd1qqqqqqqqqqqqqpgqwtdc3r4fgyfuw6j5mzg0lwgfd833e8ym4fvsv23upr.json
- accounts/erd1qqqqqqqqqqqqqpgqzsmhsv625er2w6w7rel7kmustn3u838f4fvs36jdmc.json
Hi team,
We have launched the DAO contract and listed a new pool.
> Add AshSwap DAO + pool contract

- accounts/erd1qqqqqqqqqqqqqpgqksuhk8dal6wyqje72csqma5j6ncguwj4zvdqc6xzwj.json
Hatom launchpad contract branding
> hatom contract branding

- accounts/erd1qqqqqqqqqqqqqpgqpt68cy4cde6ff2wzcfsfncjv6gxjxda8dn7q9ekje9.json
- accounts/erd1qqqqqqqqqqqqqpgqx00c5udg9uql5sgk5vswfr8cp7kalqgcyawq9xpw26.json
add framit lottery account label
> fix accounts labels

- accounts/erd1qqqqqqqqqqqqqpgqfuvnm89cv9f9t5r5e3steuwevvzyhq7n4fvs9k5m6s.json
- accounts/erd1qqqqqqqqqqqqqpgqpa9yh80fm9zad85phkuhr4cm323my5k94fvsxf5akw.json
Hi team,
We have listed WEGLD/CGO pool. Please assist with labeling it.
> Add AshSwap WEGLD/CGO pool contract

- tokens/JEX-9040ca/info.json
- Social links updated
- Locked accounts added
- Extra tokens added
> update JEX token info

- tokens/HTM-f51d55/info.json
Adding token vesting smart contract for Ecosystem, Liquidity, Treasury, Team and Advisors.
> feat: :memo: add locked account

- tokens/OFE-29eb54/info.json
- Removed locked tokens,
- Added new social links
- Updated description
> Updated description, removed locked tokens, added new social

- accounts/erd1qqqqqqqqqqqqqpgqcc69ts8409p3h77q5chsaqz57y6hugvc4fvs64k74v.json
Hi team,
We have launched the aggregator v2 contract: [erd1qqqqqqqqqqqqqpgqcc69ts8409p3h77q5chsaqz57y6hugvc4fvs64k74v](https://explorer.multiversx.com/accounts/erd1qqqqqqqqqqqqqpgqcc69ts8409p3h77q5chsaqz57y6hugvc4fvs64k74v)
> Add AshSwap aggregator v2

- accounts/erd1qqqqqqqqqqqqqpgq8tmcra2ucpewd03yhwx00fch6gh6xv886avs9knwg2.json
- accounts/erd1qqqqqqqqqqqqqpgqefgeflu7x350tae0fac2r5aesua7xmgh6avs57c795.json
- accounts/erd1qqqqqqqqqqqqqpgqkckf9dl6v0v9zecel7dtsvrsr4qr4hy36avsm0hx8t.json
new liquidity pools on JEXchange
EBUD-JEX
EBUD-GREEN
EBUD-HIT
> EBUD: add new liquidity pools

- accounts/erd10f0hq3df0ttssy0a250s4uhqtg75p22gen99tdmgtmsnj98udzvsw0lref.json
Branding the Ofero.me: Referral Wallet
0x5d94aaadc2ba315e7392bcfa5f6be205266c4c957f45b9d5d96f828c42b70eed66571b44503dbe08013bf8a348930eebd8bba439fe72b611426fdf27b5c68b01
> Ofero.me: Referral Wallet Branding

- tokens/XMPH-3af949/info.json
update extratokens list.
Regards
> XMPHWEGLD-32bb83

- accounts/erd1ryuzf08m4senh22y3rz7yl3shmeser4m5rplafg0l5ldmptd455qlll7vq.json
> Plata Network Burn Wallet

- accounts/erd1qqqqqqqqqqqqqpgqxsssdd0l5g3xpk3sfmpf0d592hdrtpvcdn3qq6y4yu.json
{
"message": "0x64613935366164646166643064666536383931396465376331366139626463343832313132613431",
"signature": "0x627f94e2a57e8dd191b63b761bd896e744d878f895fc763c0a9d481dfc5159cc3541d637fe2b52816cdde10d46f4f7857d1b0ef998682700e522dc1e006c1d0e",
"version": 1,
}
> xBulk OwlCityX Contract

- accounts/erd1qqqqqqqqqqqqqpgq5y5sqy9h0xykedqavgeette5ajel9ty6dn3qe2jqs3.json
{
"message": "0x61303636396437656562356534323061393261336533363235363765386134643464303064613635",
"signature": "0x300cec1d1ef027f9227949d8b3b3672f1adb325dd29209632330c560e776f73ce680f378e4c509935235ec134361f3c00bfa85a431c84e310a7b6b977df0a402",
"version": 1,
}
> xBulk: Ants Club X Contract

- accounts/erd1qqqqqqqqqqqqqpgqm5xzfrrfvd33wzgqpszyjweuqu3n5h9ndn3qhx5mdw.json
{
"message": "0x66363835393631393339366237626431366562613961653930666164333931323563393362393361",
"signature": "0x28f9af21527b98c89f44d4cb7ee89ecbb451639e3bcb7be67ece3b22e8d63bd68d03c8e83b489a1c91f7e6fe2bf046c08865646304583a6fb43a59ae853d1306",
"version": 1,
}
> xBulk: CryptoShrooms Contract

- accounts/erd1qqqqqqqqqqqqqpgqyak5j2up8gpk58gwgvrf97ueggx3s906dn3qtkpjqu.json
{
"message": "0x63613633666538316338383837323864393935383764386132386339616634623531663733646131",
"signature": "0xe0b4e82e6c3894391ed4dd3a0c418e6a1c8af8cdbf60b782a569a663a7ba8f57ea8db5ecd7fd78482fb4b262896ab0489c9ab073ff2a10c331d623ed0a469f00",
"version": 1,
}
> xBulk JOJO Contract

- accounts/erd1qqqqqqqqqqqqqpgqvmq3wdm4l74vsynyhw92smwgkmdrkwh0dn3qqzcsrt.json
{
"message": "0x61363734343438663363333736373661393266363830633134353932666132333230346665636630",
"signature": "0x2013b37239c893f418cfd64fb7b9ff9995347aff6f5c0df9d2eb6aab0d7a38dedfd4f3572990157e6f3cfe779a433b516664d792a172344907de493d06ba8c0a",
"version": 1,
}
> xKingNFTx: Market Contract

- accounts/erd1qqqqqqqqqqqqqpgqsxu0745t995t9gxylvt9xls07dssvnjmdn3qn7sj4h.json
{
"message": "0x34366665333662373564323836636533363866623163633961346264333363653837353033386330",
"signature": "0x6d16b5a206fbc5fe4884f7c43367f83229857cde4cc42da3a26b2d5809d2ec5718a1c5ec53a340ce0b308829e5755abbe2017331a163860d2e9217e0aaab7503",
"version": 1,
}
> E.V Ecosystem: EvolvedOAG Prime Contract

- accounts/erd1qqqqqqqqqqqqqpgqadwtwhngann2zjze7su9vhuw7297j7pwdn3qgp49dj.json
{
"message": "0x35356239303062323633363936323834646263333331313830326266663566366135303331393364",
"signature": "0xfbe7052a7417b88b2cede97a6619ad791c24b4e140cbe8249db8039a7ce702f7bd7bb93976d0e1ae9d47e3aebdf1d4a0435a3e2dc168d380649a97d673b60c03",
"version": 1,
}
> xKingNFTx: Xvolution LVL4 Staking Contract

- accounts/erd1qqqqqqqqqqqqqpgq6sqyxxr9mjc3w90czqmh4dwdkfg9yz39dn3qqkylyk.json
{
"message": "0x64396161333433656436386463353766616262386535346131616632303539363435366131646465",
"signature": "0xc9ef06d62ca1a83e8facb2c56856dedc68864111ddf38ca151d66c7049b335fb88bc0513439d8065545b75024a250f03a36e06ee067e9d5624d2f8da48fe9e09",
"version": 1,
}
> E.V Ecosystem: LP Contract

- accounts/erd1qqqqqqqqqqqqqpgq634wcv59j0pn6fn6629wu7m30p7xagmwdn3qyjcfgl.json
{
"message": "0x64353466336162346666333535353931646232366134663665323637353836386362383030333233",
"signature": "0xba8df304306546aa813dc860a8b849c00a188c32488e3270c9a9bc119f251d6fa99ca9bf8c80c4fb84856ee668e7103e6cbe3bc666b0f952a370171366f67206",
"version": 1,
}
> xKingNFTx: xKING staking Contract

- tokens/CHIBBY-dfdbb3/info.json
> Update info.json ($CHIBBY)

- accounts/erd1qqqqqqqqqqqqqpgqp8hxhxp2axvax97yudss5jj6gzzq90hkhdrshg8hw2.json
0xec1d54347a0bc46788959872719fc96c76190d281d89f926164085d1dc3d7c76293cc7ced099ccb5639ae9667a27c05a5a0b8e2acfb499f2713974befbe1df0e
> Add assets for contract erd1qqqqqqqqqqqqqpgqp8hxhxp2axvax97yudss5jj6gzzq90hkhdrshg8hw2

- devnet/tokens/EMR-6310dc/info.json
`{"address":"erd1fsuk7wy7vhzysfntpq9l3wj5h6snz9ft30cgt22d35hdwe7n0t9ql8cmcj","message":"0x30383266643561333931336631623266393131613266336232313336623833313432653565623738","signature":"0xd1105e0ddd2c6b8841781b136b811b8cc34241268dcda2122130596e14729bca73065a54bf6305eb8c2ad53182e43aa2a8f5e7c8f46f6b2ab4cf4d30492e6708","version":1,"signer":"ErdJS"}`
> Adds devnet locked account for dev wallet EMR token

- accounts/erd1qqqqqqqqqqqqqpgq2ymdr66nk5hx32j2tqdeqv9ajm9dj9uu2jps3dtv6v.json
- accounts/erd1qqqqqqqqqqqqqpgq389gc8qnqy0ksha948jf72c9cks9g3rf2jpsl5z0aa.json
- accounts/erd1qqqqqqqqqqqqqpgq50dge6rrpcra4tp9hl57jl0893a4r2r72jpsk39rjj.json
- accounts/erd1qqqqqqqqqqqqqpgq6zat6jefz9z8n54yag8xmz7jw20vlv3x2jpsxms0sd.json
- accounts/erd1qqqqqqqqqqqqqpgqcg4knmq77wxlnkzjgqpjjyk582smte7e2jps3px0sk.json
- accounts/erd1qqqqqqqqqqqqqpgqdt9aady5jp7av97m7rqxh6e5ywyqsplz2jps5mw02n.json
- accounts/erd1qqqqqqqqqqqqqpgqj7yq0qysvn2xye0ywzkl0qn95wz8ttcr2jpscpfazv.json
- accounts/erd1qqqqqqqqqqqqqpgqkxtzg0cd02eahr3tac9efl25cfr9yj4t2jps3xnwda.json
- accounts/erd1qqqqqqqqqqqqqpgqtce4z8zzz76xjht3hak0hseshcmj3ush2jps2exxjn.json
- accounts/erd1qqqqqqqqqqqqqpgqv692rgsd6teaq78nufvgkgjnmca6anqn2jpsphphj6.json
- accounts/erd1qqqqqqqqqqqqqpgqxrkd0t4lzq6rfdfg03g2ymc7ygv3ayqc2jpsezhzt9.json
- accounts/erd1qqqqqqqqqqqqqpgqz55dum74jl0nqxgs7z5d84f448tx0zwp2jpser4d8k.json
- added the xexchange icon where missing
- updated the proper xexchange icon where the old icon was still present
> Update xExchange Icon

- accounts/erd1qqqqqqqqqqqqqpgq9kaudhjde4dmvh4rvtysmyzj7f2ux8akdn3q5wjaht.json
{
"message": "0x62623636326135333862346463303866313339646561303766373338626664616165346639633061",
"signature": "0x0011b383b61137cfdf137102dabd4a64e505799d2945bc608e3b6ef2f62b57ca8a9d868c7a089821ba1e64cf853ac3c2e46ea4e387397f8a30963ed1ac65260e",
"version": 1,
}
> xKingNFTx: LP Staking Pool

- accounts/erd1qqqqqqqqqqqqqpgqyacdqy36t0yltjhnur9x486xjg2zu8vydn3q7ueyrs.json
{
"message": "0x64626265636562633439643666393834653166396662313066303431306334326661323165646363",
"signature": "0x1c2f119e067ee47609e4b0caf10a7243777eff2309b182671e04901cb8412da7754fc4c3d75a0687bce8638d145a63c2d01e41a109ea593de443a059b0298107",
"version": 1,
}
> xKingNFTx: xChiefs Recruitment

- accounts/erd1qqqqqqqqqqqqqpgq3udg8w8c9r5fvc8xlf4glcp7ymh9ama2dn3qzks0em.json
{
"message": "0x62633337653163393134373531306464303733376539393964383865613532646535333234316466",
"signature": "0x2ca55d995d3184a084c5c97c79297959010539a2ce2dc63fb1dda81b8aa56a9d57f25f65edcc071e08bf7ff5ace7bae5f163c600d779692cbe9cce5fc620dc04",
"version": 1,
}
> xKingNFTx: Josephine Bridge

- accounts/erd1qqqqqqqqqqqqqpgqj70cd05e7zcsswjh653e3avapclqjlrmdn3qxf4gj9.json
{
"message": "0x38366334653033346331303031353030323030643963336266313735383766623765633964656366",
"signature": "0x3ebc9a171632c43773d4a2265b017e0aa90710fe77422a6ba99365e6cea05baa32355418bf04f15ecea8245a998cdc6970e36f88d80a291da8f25c72c3440809",
"version": 1,
}
> xBulk: RoadToLibertad

- accounts/erd1qqqqqqqqqqqqqpgqlq9wjml7vcgvlyunxw3q0tktxjpxuztadn3qmxjv3l.json
{
"message": "0x30623832356338333066313733623361346634623238383837663262346637333463343737643437",
"signature": "0x96cecb577c2b5274134d1399c228c8ae4ec6a6c4f250f434558903a6f3aaf892708603c1adc2284f06eaf29c7ad0b9776cbeeb270066907eb93539b367500407",
"version": 1,
}
> xBulk: JOJO Protocol

- accounts/erd1qqqqqqqqqqqqqpgq824whxfh39w79qwqk7zl2smt6mzxpw0jdn3q93nvrd.json
{
"message": "0x32353235386535636232613239653837363166393335343063613564346135333832653463333632",
"signature": "0xaf7cf603966618b8677b3a71d311825cb3f0fefc5687f80154a91be7fa338196f5bf05da3cf3006d6ca66a475825be2c1a413b5709a2f9855206a24101c5bd01",
"version": 1,
}
> xBulk: AndromedaApes

- accounts/erd1qqqqqqqqqqqqqpgqaecxurn27e6gd5lstegj036shqdr82qfdn3q5ku8up.json
{
"message": "0x33303631393836303833616261643135333833303361376364366134333330653732653632626636",
"signature": "0xcf3e35ea29c1e274aaee0d0dac4ed3e898618e3b76626fe244a931d8b95c1103d6a1d78fcc3dcc6de5749942c8d6fb3c2fae244699c493779cfac0add520ee03",
"version": 1,
}
> xBulk: xPingouins

- accounts/erd1qqqqqqqqqqqqqpgqd88sy0snq6peges7zhl6sq63upnp6ddadn3qpaxxw5.json
{
"message": "0x34613865383338663566376534636533386239623831326433326135383662343238366166626431",
"signature": "0xfba07051007ea2588c2bef869875bc4d47fdb03cef97495daf2d5494c3b4314b878e9bee06924751039dab1920fc926bef89429ac67ba1673252364fb572c504",
"version": 1,
}
> xBulk: DOT9APP

- accounts/erd1qqqqqqqqqqqqqpgqn9hty0se72h4nzgncklanyyvqt47nacvdn3q5l6eqh.json
{
"message": "0x39623666343763653732613465306466363635303836643433643939346232316634633238383534",
"signature": "0xd72be0fea4c83188c39948481df016e40dc5b0353c4f2a2c105f738f7a4d359dfa834fe6072c2ca9312c05efccd3c93819df9ad003ed6354add1dfd45f33360d",
"version": 1,
}
> xBulk: DOT9APP/DAILY DISTRIBUTION

- accounts/erd1qqqqqqqqqqqqqpgq0jpj2t60sx70kp9298zw0nv6aj9txhytrsms20tt2p.json
- accounts/erd1qqqqqqqqqqqqqpgqtvmprk02xqkkw9mg5sg33ydztqj34dwrrsmsf02v7u.json
- accounts/erd1qqqqqqqqqqqqqpgqx60rs66pp98vhk44vhg7kxssd08ylk26rsmsd83yw8.json
Added assets for break multiversx contracts
> break multiversx assets

- tokens/TCL-fe459d/info.json
Add Public Sale vesting contract to Locked Accounts
> TCL-fe459d - Update Locked Accounts

- accounts/erd1qqqqqqqqqqqqqpgqd0e2nwxe5nx3hu6zupmzy0mhgyvrqmtv4fvsff5vsl.json
Hi team,
We have listed XOXNO/LXOXNO pool. Please assist with labeling it.
> Add XOXNO/LXOXNO pool label

- accounts/erd1qqqqqqqqqqqqqpgqugnjt2xzwyz2h8x456u2cqpjzhq9uc6k4fvsvq0v22.json
Hi team,
We have listed XOXNO/LXOXNO farm. Please assist with labeling it.
Signature: 0x1c4c37a374c4634822428ff7aeaa514a36f1a53ea29fc6478d6819fb6d3c5673fd519d81445cd886942489ad966f4cadb9e96fa81088e9adbe927c4774c69a0b
Commit hash: 438c990fde1e2e5778b60108748612233dc582d1
Wallet: erd15xh20eyfdaqurvkqy99uf56w0qmcwy8jv0twmguuxnn6ypax4fvsvpgp7n
> Add XOXNO/LXOXNO farm label

- accounts/erd1qqqqqqqqqqqqqpgqfw5l86j2g0qsn9r3xfp89l692326qa44dn3ql4txsr.json
{
"message": "0x62613537616139393337376564303561326339643366626561386362613031353361613330356636",
"signature": "0x88666767d0953a98963bb563213367ccf9d9f6fdbd373b9554b5fa6a20cb5fb32c2f0f982c61c5fe97ff2d43cec2791ff7501df7492b436e68c815c4ba373c01",
"version": 1,
}
> E.V Ecosystem: Badge Staking Pool

- identities/oxsyai/info.json
{
"address": "erd1eg8syhxp8e0535zh8vny9z47f2esft2tm0m0a5wlhdgee8wx380s9kje85",
"message": "0x61343763366635313730363537613238383736323833646430653232393435316565376535353739",
"signature": "0xbf81ce20fd2b26a2f59b39aa57143b170635fa4d8810791e34a8e0b38cb147f38188f38099a4429314207e667b3ec16c80e310e3a2732499672f875c922b1406",
"version": 1,
}
> Changed Foxsy AI staking provider APR from 4% to 3%

- accounts/erd1qqqqqqqqqqqqqpgqadsz6y4feh6fge868tk65hamhf2pwsxt6avsyhtppv.json
{
"message": "0x37643961323230303061383539653433343735326530663239613133346631366634616163623537",
"signature": "0x57fc1423c68386a6d154e7100d389e1860e78b21efc06d8b21db0fefb9f9d227e3b95af47ef6f574d4dc623f26a0c46b0b41ddc0a0b1a9022fee4c23d8429900",
"version": 1,
}
> JEX: RARE-JEX LP migration

- accounts/erd1qqqqqqqqqqqqqpgqxpkagqaqp9xz0cq5cq9a9fjtxde7d5aydn3qvnvqls.json
{
"message": "0x33663033663966396132303236623465366364356231353333636130306434303034343731346365",
"signature": "0x0ab0dfae8fc8ea92a9ae25f4bece850f38a6961a1d9ba32dcd71aefc7fee8e8dcf373ced0b4b217880d12ea4886272759de2842e38c99ef13dce95e2e0f1c709",
"version": 1,
}
> E.V Ecosystem: OAG Containers

- accounts/erd1dmf9w52f5jar2d9qgq05yjaj5e2at72zer805kp99hwjz4mn40aspcswsw.json
Hi!
Here's the signature of this commit:
```
{
"address": "erd1dmf9w52f5jar2d9qgq05yjaj5e2at72zer805kp99hwjz4mn40aspcswsw",
"message": "0x39336562356133343561313239656334393361326561316330633539353839383134363836303133",
"signature": "0x2dc15dce6e32ac4fbfde4a5c93717a8cdd7c6b8338050846ee2536182ae234eeebde4718031fa55820181d1ab60ef33766bb5a38e87963a2fa8113d24b884202",
"version": 1,
}
```
Thanks!
> Update Boogas account branding

- accounts/erd1qqqqqqqqqqqqqpgqvvhld0zalzp6ga660k4czv5x5kqanlxtmp3se0hx80.json
{
"address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
"message": "0x34363531653938386434326335306564353632343839306433653036363466333536373131623265",
"signature": "0x43994c25d39fcda9a1c90906f8381036b03fa7bd6c9bbbcb112dff6bf62d385e2ddd5a03e6558ca085df326fe69bb8bc588ba86a0057fec7e5a5c5478eda9a0d",
"version": 1,
}
> Emrs emr liquidity sc

- README.md
Docs for adding custom URL price source for tokens
> Custom price source docs

- accounts/erd1qqqqqqqqqqqqqpgq4he8sd0hatnjemg6mv89w28h0rc7yd6jrpeq92s428.json
{
"message": "0x33313862363661383033333734336635326163333739303134323534393634306438343064333437",
"signature": "0x6100a1a68befe50ad218e78294784a6da81820ca0b0548e289fb51f5fad2074b773060306975afbd77488e6c763cb90c48edf7282cd99a2f45c661dc64cb9e07",
"version": 1,
}
> E.V Ecosystem: Roma Tickets Ed.2

- accounts/erd1slm0438zzr8hutclhkysnjslxuxq667yvjq9jdwhml7dwsw9xqustr4d0c.json
0x7c45168583e853be7cc33deaaa559f74cc1487d7ad9e4174b04ac111492c11e8471f57fdeacad9d22d1ef50b179cc56f00723d512aa60a71c4215d916503a800
> branding erd1slm0438zzr8hutclhkysnjslxuxq667yvjq9jdwhml7dwsw9xqustr4d0c

- accounts/erd1qqqqqqqqqqqqqpgqa3vfumuxu30xhvucyptjyjla69ftddcup4hqjh662q.json
{
"address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
"message": "0x66646533643735313765313464343563626332316436633834323837323961393832333137356439",
"signature": "0xf7f67914fc29da0cdcd434c44f4aa85c2a81c2ffc20d618478b4327f0094b3261e08757ef8fcaab611272e8e4ab310ff6243c495698ea46bdbe057758c5bb40d",
"version": 1,
}
> Emorya Investors NFTs Marketplace

- accounts/erd1qqqqqqqqqqqqqpgqhst80r3txn7wa25v62ejngcj0ptm9m8v6avsskjz5k.json
Hello @paulmultiversx,
Please approve this PR for branding the SC for OMI/WEGLD.
Here is the signature for the latest commit sha:
0xdee0b4ca7c3a58b647d875d309eb6cbf7e640e28ed0dbcc647b2eaf42a04bc4cce393cbae986709d4b1b3fb9013ef637ffad5e2ed465a1ed81062e7c5fa1100f
Many thanks in advance.
> Add OMI/WEGLD branding.

- accounts/erd1qqqqqqqqqqqqqpgq8dhq0d5t2ck8yagrnwghgwmf38egse2t6avszxwx4m.json
Hello @paulmultiversx ,
Please approve this PR where we added the branding for omi/wbtc.
Below is the signed latest commit sha:
0xa0b9fd3f2c0b94b16cf3f3a01e73ee9ebd736afe017b13a89fa6c8f4a74372ac2fd65d2871dd67a589ca30a59a1edb87c1609e550d688c390b779aa2b2233109
Many thanks in advance.
> Add OMI/WBTC branding.

- accounts/erd1qqqqqqqqqqqqqpgqgheln00y7mtyr0kqms4qt4ynz0nrv2czxp7slkap30.json
{
"message": "0x61303233366438656537306433353466646631666332373430613930303137623133616336323337",
"signature": "0x713648b0fe6eac1b64863be104345ca3b810b8217884b88ec2b845e031c34915d3e5a53d2419664a5126d534c74d926a699afaca8279976455c92d4dce20a10d",
"version": 1,
}
> xKingNFTx: xTrading Staking Pool

- accounts/erd1qqqqqqqqqqqqqpgqusp50r5jqw79e7vd9x0dsl59pcm2yxsvxp7slhy503.json
{
"message": "0x66663238323263313236323265616233323430313962313737656662353366353935313633623134",
"signature": "0xd4aa39a0350080db6544db697de159fedf4e10ddb0f05e82fbc5b41ae6d71c0df3ac53f661018315ab9ec8cd57bb629707450c0d70462d59abfb23810730bd0d",
"version": 1,
}
> xKingNFTx: xCHIEFS Staking Pool

- tokens/XMPH-3af949/info.json
{
"address": "erd1cwt0rw5aqgcfn85pp3lv88x6expfj8zjh5jat5w4dhc7fg044fzqnfhs7t",
"message": "0x61626534653961663939383762666336303731643965336232613464323432326163643136326636",
"signature": "0xc17f0cb35f018e1e2f055fa89853a1893a722844ae29c4eb369ca669c7367b66587cc1f0c955e288f5117c6d43783f5cc1db154341381bbcb7d0d212837dd902",
"version": 1,
}
> XMPH-3af949 new website

- accounts/erd1qqqqqqqqqqqqqpgqavnmtujaa9f6qkepexpurphtrhn7r408ldhsvmgr6y.json
{
"address": "erd1r8n7crxg92pluw77hmyuew0nkauxzeg72gdrs09688lglafyldhssf63jp",
"message": "0x61333161353462366430626331376434383063323763633365666536323262623436336137313030",
"signature": "0xcfae3eb198617ba9fd903d1e099f10641e0f0d218ec5ca322253a7bc5801f907ca144ea8d993b82178e7d7ae151bcc2ad665255677f8c2c908c28205d99b0605",
"version": 1,
}
> BHero: Inspir3 Launchpad Phase 2

- accounts/erd1qqqqqqqqqqqqqpgq6emnyqqxdrkwjegdulsamrja2tttwpj3wmfs9cmszf.json
{
"address": "erd1szcgm7vq3tmyxfgd4wd2k2emh59az8jq5jjpj9799a0k59u0wmfss4vw3v",
"message": "0x63343265316162313230356433323564326631643636643739663135323238336131313166356138",
"signature": "0x20683e4238dfd80306efc245032d79478305e1ad1651b478a90ff44ee95f3068d49d0dafc8395e82663caa4267a4933d46019a8f45b7ad099d50b992e82b1b0a",
"version": 1,
}
> erd1qqqqqqqqqqqqqpgq6emnyqqxdrkwjegdulsamrja2tttwpj3wmfs9cmszf.json

- accounts/erd1qqqqqqqqqqqqqpgq27gr6uyrta9qc33den2uchu3vlcl2v3qwmfs8dtgc4.json
{
"address": "erd1szcgm7vq3tmyxfgd4wd2k2emh59az8jq5jjpj9799a0k59u0wmfss4vw3v",
"message": "0x62353736633766313838316636653931336466333530633161383834343764313834326632613761",
"signature": "0x4c19a12fb1ad8441ea90e07ef262e09dafce6a1e9321a669c9e520f7eab7bc28b946b0914ccd266b0ec93951c436888b3113f2d5c5dace73379d0239ceeda70f",
"version": 1,
}
> erd1qqqqqqqqqqqqqpgq27gr6uyrta9qc33den2uchu3vlcl2v3qwmfs8dtgc4.json

- accounts/erd1qqqqqqqqqqqqqpgqsvmrdrtnxfgmphexegrae93zf28n9dnywmfs8uy68v.json
{
"address": "erd1szcgm7vq3tmyxfgd4wd2k2emh59az8jq5jjpj9799a0k59u0wmfss4vw3v",
"message": "0x64643532326230376462616438306437376362373363323135386465633564393338393364396165",
"signature": "0x130cc30e805f8884b4a1c3abaf5deabbe9a7a9981c673f6cb0ffaf841167bcdda9ad4b0af99fefaecf72aad65c78861144d9b07ab0f46bbe48a471155368d00d",
"version": 1,
}
> erd1qqqqqqqqqqqqqpgqsvmrdrtnxfgmphexegrae93zf28n9dnywmfs8uy68v.json

- accounts/erd1qqqqqqqqqqqqqpgqxslnus9asdhmujwf69znhq04wjwafmagcrtqrgmyh8.json
{"message":"0x65663865343938643235303234373431306363653163353262613231353061306239363032633730","signature":"0x315e8ca47b4d0304c0f295284fa308d89a898ec97afa3028c8c3c7a7ae86973a7e1b30e31afe050f81e33f94c67ea8c776141e8c070616c3c469c4e4661cd00f","address":"erd1nj250ynk88vkhkch82qcesmd30duf0wkw0zyp8a26gtkv3n7crtqzxm6pd","version":1,"signer":"sdk-js"}
> feat : add tada burn sc

- tokens/BOBER-9eb764/info.json
Hi Paul,
As this token is owned by the deaddead wallet, I cannot provide any valid signature for this commit.
I think @mihaieremia can confirm that this update is legitimate, if you want other users to validate this PR.
Thanks in advance for your help.
> Add CoinMarketCap URL on BOBER-9eb764

- tokens/FOXSY-5d5f3e/info.json
{
"message": "65343736383930663365333162653531323266303833656461643536653361313365303132396238",
"signature": "de79ac1b31ad2e05f0ad44d1f2eb9df76cd4409767ef8c65dcfd5308626b941887525054558089ab9eb3b86acad416d452236d2157232a99faa2b5c878ecf006",
"address": "erd1m767j3xs0e53kxr797rwl4pchydatcyqu3v09tl8202samrz6cys8rezef",
"version": 1,
}
> Updated locked accounts for FOXSY-5d5f3e

- identities/egldsqueeze/info.json
> Fixed typo EGLDSqueeze

- accounts/erd1qqqqqqqqqqqqqpgq782vk9ql6q336437n55u7535v8jj50eydn3q7r3apr.json
{
"message": "65613738653431633639613038343461323035303838656130303462353138643263393765626437",
"signature": "7f1af7b6cf1dc662051b95355b7523a84418adde78fa9c74aea95c86491129fa67966aee0eb901858899977dd043ff328fbd823391a58303449c84c763b6bf01",
"version": 1,
}
> xBulk: Masstino

- accounts/erd1qqqqqqqqqqqqqpgqs2y5luzq0kf9vn2ja642n446ddspknjmdn3qpncjgg.json
{
"message": "39336430306336666362306535373038646266316238386465393037376362383835366538393533",
"signature": "49e1367a6c43d0e4d0351e2934a098112a7e0cd1e152b47c78c90401d216880a61fe351ffc67a1d7e92f02eac72932a58a8e6aee205819802d6f685a2f5b8108",
"version": 1,
}
> xbulk: Pittz Monthly Profit Share Rewards

- accounts/erd1qqqqqqqqqqqqqpgqsfj4alkefq953u4ldl2jfsnhn2r58fycdn3qjz7my5.json
{
"message": "64636165366237313232313861313838313531623362643164336430326236363239303937626165",
"signature": "d3b48e83bba91daa45ff8b87d5b74f3aa414ab7620be65e2c2f4be268dbcc1fb81769b83396724cac2a3107db30c77fa19b60d728d82c57ce1b1e638ccb40709",
"version": 1,
}
> xbulk: Today

- accounts/erd1qqqqqqqqqqqqqpgq5d2pammlumgtlhh9ugersqkd9nt4nztqdn3q3wt3v3.json
{
"message": "39613862383431346366326561333737366132366666663931363964383230376461346362623937",
"signature": "fa47c2aae8264c954d7516f057723b0cb8356f9cb8d2f8a3e49639127c5066be77b0ec92b23a323ab723229d890b762f0bca1efa81f5a315bdf03f7d94ea700e",
"version": 1,
}
> MAGAX distribution

- accounts/erd1qqqqqqqqqqqqqpgqae0wn6q04sz6c3zmz265j4tyuc4dyh88dn3qx8lhcv.json
{
"message": "63386265376235343432353739303430356664663730353237323134653337663062666664363630",
"signature": "864d4a514af92abee60d5100f10094ed76df412b2269fe7d51ed1e9b9e89e0e3fb549e3ef531bd9105a4e74b30913579ba1bcb5e3d747b4e3ff6a6c6abcf2d01",
"version": 1,
}
> xbulk: Pittz Incremental Rewards

- accounts/erd1qqqqqqqqqqqqqpgqpppwvamys50nx8nkzyuvslhd27da7dd9dn3qxtf5ev.json
{
"message": "64373762386330623634323661323962346633623832363134623839616533356438633565373764",
"signature": "cb718b6913533b11ee8d695b441adf22badbaaab1a55a47cecdcc9538b120949f781fc910fd3f9008193b8f379c94e2ba0dd19328990b09e381d1870747fcd00",
"version": 1,
}
> xBulk: Triskel

- accounts/erd1qqqqqqqqqqqqqpgqxa24yqljd04s07m9s36plwex8p68hjq8dn3q0fur66.json
{
"message": "66663763346334366366346365326239396430656132666434346166656135393839653463333533",
"signature": "5a80b080999d14d61f110dd28f607fb851ed18397a4864e7ee78252fa5e45307723fa4cb0ebf5745ade7578522823d846cfc904250e0a8d54a9fec13cd962c0b",
"version": 1,
}
> xBulk: Hug-O-Matic-9000

- accounts/erd1dg6umnh4yxw4yjtl9k7n6plhcmhsrghpyg5vyl928l96crs7pr9scashvp.json
{"message":"0x36613366666263343131346435326437396361613730633161336162393162633962363731616438","signature":"0x0d5ff2872281693565ad1756a2c3eccf22a30b78ee70b1262fbfada460645b4dae12023692d5cf5f71ea0288f3615979ec232fd71d884a168ba0cdf6039cfc00","address":"erd1dg6umnh4yxw4yjtl9k7n6plhcmhsrghpyg5vyl928l96crs7pr9scashvp","version":1,"signer":"sdk-js"}
> Update Ofero Network Cashback's wallet

- accounts/erd1ln0gy7k6a2f7999rathctxxd8ehfhz8n5tzwhg7rfrxrh359294qxrampt.json
{"message":"0x39613930356632626364363438653937346237353135356264616564653264346339646664616332","signature":"0x50a74053d9f85ee07d46cfcc7bfe8ebdead952ab30b381380c8e6ac07a9fcbaf7a0c89d2332c7ba9a41dfbea72ed305ef6f9d264ed8e71a16bae47a07e2b2808","address":"erd1ln0gy7k6a2f7999rathctxxd8ehfhz8n5tzwhg7rfrxrh359294qxrampt","version":1,"signer":"sdk-js"}
> Branding Tradesilvania Ramp Wallet for Ofero Network

- accounts/erd1u57p4wu5t0tk8r5gqg6x9sa0kg5wm6jq0yad85fehuw3levm8n0s8kcard.json
{"message":"0x30356639396636643537373330326336666433316531313666376664653164613862323433393165","signature":"0xf29e0aed08a43af303db03c605bf447a14bcc733aa508c273b1475614c70c61dc343ed8595fe0969cd7510c6386af3199ac595f6728e1830bafa6c9b6830ea0c","address":"erd1u57p4wu5t0tk8r5gqg6x9sa0kg5wm6jq0yad85fehuw3levm8n0s8kcard","version":1,"signer":"sdk-js"}
> Branding Gift Card Wallet for Ofero Network

- accounts/erd1qqqqqqqqqqqqqpgq3c43fl0we7t03lcrarmvdjwfq59wsllw6avsmjdjqv.json
```
{
"message": "30353037653437396139666161633564393736316532373338353639336164376465663939323035",
"signature": "8e879732d052bd085d1c4a10658c10a80d6d9a619e4b0334c3be405628afd89a7185126358de33cae6bc70d6708ee8e39e79975726e2d58673d7c3c10aaf8407",
"version": 1,
}
```
> JEX: add dust converter account

- accounts/erd1qqqqqqqqqqqqqpgqntwj4zg8erj4akd56s00xccekjuae2rzdn3qvv677r.json
{
"message": "33393633326334613132626430653065373035353365356639333239316162376364323939316265",
"signature": "113cf6dc7610dd369896e43fd1ad2375405eb60f76ceba7325fb289298bdf0beca2f0cc14e8602baad34c0b388bd35dbb77cbc94118e00b3738500e571730c0a",
"version": 1,
}
> xBulk: Pittz Weekly Rewardz & Burnz Distribution

- tokens/JEX-9040ca/info.json
```
{
"message": "39396666646232353437653437636661373735326661323566343062346565333731653332653937",
"signature": "45ec24e9543b662b761ad9ae9f786ec6929d61c70f11723d1b895b533fdeeb067f79f06c7dbd7496e42bbffc58560ac82a7d040bed5f46e6b32cdf188876f90e",
"address": "erd1hmfwpvsqn8ktzw3dqd0ltpcyfyasgv8mr9w0qecnmpexyp280y8q47ca9d",
"version": 1,
}
```
> JEX: update token info

- accounts/erd1qqqqqqqqqqqqqpgq360nakqgsp5zkmguptucpjy6n4n3du7e5snsd2swzq.json
```
{
"message": "64613031326631366433393936323231366136636566646264383161363966336266636465633366",
"signature": "19c97ce5b3a87dfb2c66b8927c767dc0a974f267c7aafc7c158bde46d2df223a3c7815e04d7b9d907f840184905be773c6a6c61961c079ef5185dda0b06ae908",
"address": "erd1xave0lcavwmu64pfseuk36mragmmvxfjwq7eqna4ecser0jh5sns7mnc4f",
"version": 1,
}
```
> JEX: add JEX aggregator v2 account

- accounts/erd1qqqqqqqqqqqqqpgqyfxmhq632l3dv8h5898h49aswxuyxgc2899q85zdwg.json
erd1qqqqqqqqqqqqqpgqyfxmhq632l3dv8h5898h49aswxuyxgc2899q85zdwg
> Add assets for erd1qqqqqqqqqqqqqpgqyfxmhq632l3dv8h5898h49aswxuyxgc2899q85zdwg

- accounts/erd1qqqqqqqqqqqqqpgqqx20mehhvfe2lhyspdeyjnmmdvlyg8k26avsk78e2a.json
```
{
"message": "61333935383264613939366430383630333336316136343165623831393666333261383963373130",
"signature": "146524a298695b23819a4eb3df29b178c825a6eb69675d29b5f7639a4251ce28f618926968087c15f578e8bb0078287f150b912b2bfb90a94aa56c4959c2e109",
"version": 1,
}
```
> JEX: add raffles v2 SC account

- accounts/erd1qqqqqqqqqqqqqpgqypzse2xtacw5a2wnjv2v2n7sumyymdm96avsv022ct.json
```
{
"message": "64643237363565386438353436396632376137316234343566663866653665623034396666323062",
"signature": "9d35c1cb8e5a1d3f13a58ebbe346fd62555cfdb363f978d6e19f89c85ca9f2c053d8ff856fc6963b983d8a5c1ba4154c399ae97aceba03c4587221a0366d340f",
"version": 1,
}
```
> JEX: add account for USH-USDC-USDT stable pool

- accounts/erd1qqqqqqqqqqqqqpgqw7sqzzd7s6a94zngm3ffdv2ypnayqx78jnxsre5uew.json
{
"message": "33613539373735373539343338313032303139306261396437633632643934656534336261316466",
"signature": "6697e77c555d7cc4d5347275510ffdca0669076129e07bab36ddd89fc75a83117c2a9a44820b4ba606338dc99c180cd225158728a196f8014dd029eb75ffa50b",
"address": "erd176efse0xdsrwu5kwwx3uzjy889ce7hqultxsrlldztt37zs2jnxsvncve9",
"version": 1,
"signer": "wallet-connect-v2"
}
> Website Link Fix

- identities/ninjastaking/info.json
REQ: 72caed3266e918342fb799d80f7da1e1bdb49660
{
"message": "37326361656433323636653931383334326662373939643830663764613165316264623439363630",
"signature": "ac9547e3d306685c107a25a9b3f4d29906d05f30eb5c87e06e251847529d4c5ed08c1b8bb07a8a60d1e9162d04885a7b78d1bc034c198ade1d4575c3d03a1b04",
"address": "erd1dygd087n6wrdqlvlnp0xwpexg638qnqxt3wk80cn9uzfy4c9z7ase0y4x2",
"version": 1,
}
> Ninja staking

- tokens/GOAL-02ef1f/info.json
Hi!
Here's the signature for this commit:
```
{
"message": "31313530343334653263636631383266643136303636306364346165383333343435663938643633",
"signature": "2e0301ead3fd0a04e9e88cde7f2e2db980f4dacfc512965b008de200a4eac13e5b0c0e4ce933ae61534c9c9f65fd05b3d84073b48f5e7df3c6d1dfad996b8107",
"address": "erd1y36pavnrgsz0jvy88zyxd5dhgt640unvwc9xjchpyk5q8e89mt5s40849p",
"version": 1,
"signer": "wallet-connect-v2"
}
```
Thanks!
> Update token GOAL-02ef1f

- accounts/erd1qqqqqqqqqqqqqpgqnwddv3yy0m6w2w0zxwa5s74f5ukcsdtk6avssg5uw0.json
```
{
"message": "35316130623265346261643937623461373330383162316638336663343539323466626532316566",
"signature": "0cc0a89a6af007614066784f5b7de0092b1fbb481b7916acce2b6e3e49de16688b064fa34d8d9093a1604b694ffd0e77da66d2d331e2545f21a56b3cb73a9901",
"address": "erd1ssruj9rjy529ajqpqfmtkyq422fh2m4zhkp4pmfng3aad2h7ua2quydm30",
"version": 1,
}
```
> JEX: add account for WEGLD-USDC LP

- accounts/erd1qqqqqqqqqqqqqpgqvx7fj3spvc4hj2n9vlwluw68643p6dar6avskfct66.json
```
{
"message": "62653238373035353832363331346434326461323665333739316432616462643237633035336635",
"signature": "eb506aeb1b25575a51917b1d179c6614be1afa5756e19cbce9913f270a965979aa1560409baa51c5e014f36329a0deb1c913a0277a220465fe1be093bf65f301",
"version": 1,
}
```
> JEX: add NFT staking controller account

- accounts/erd1qqqqqqqqqqqqqpgqeu0tkupaqr64h95jtnk7pnhjnjs4sn9l7y9smjl4n9.json
0x7f58d8760a27676a80263d82c8552b543d828a4cd0bbabc88ddede4bdaea9cb88d84de7a9b4bb4a980a039466776819cd15201aebca97561af3ba424735e400a
> Boost xp modules2

- accounts/erd1qqqqqqqqqqqqqpgqmksd4gl3xau5eja42sp6qmrxewxgj0ny4d3qfksmrq.json
0x8d2f766454f96f92cec254da7cbc932a726da5531c39cbcc7dc8fb33a70605a778e4be03cd40514f421da181bd800f18be44d3c9b48bc6d0d218b083ad7caf05
> Boost XP Module 3

- accounts/erd1qqqqqqqqqqqqqpgqa7hy7fe8khlf5lhg7huk3nlqusu2xa6kmp3suhgj4h.json
{
"message": "31373231316361363063336236323165306534353036323736333765633135363736306636326430",
"signature": "752860f5900258435be1975a378240f7a2567bca76df94d93a3cc4020dd8aa5f56b2654933675c493d69ddcd4ad7fbb1b54da1d741c4d541f12ea7253e4f0e0d",
"address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
"version": 1,
}
> feat: sc changed

- accounts/erd1qqqqqqqqqqqqqpgqfczguuad5nfe66a88k90wjrhk8ud733gmp3swvgzrg.json
{
"message": "35393865666333376266396436646431643035393835353832656633346437663661326533376138",
"signature": "1526bbfb0d24caab8ad54d2f5da7e331fc9673e51bfe2c8d1e2703903a52285f1f21ae10ebb1eec830b1f3b2bdd0a48e3ee0656bfb0fc93f3846a3ec521d6e07",
"address": "erd16arrrc0daw46y52prfyz0httsdy4dr0a34hngdedz2fuzvsfmp3sld67zc",
"version": 1,
}
> feat: marketplace branding

- accounts/erd1t8p8eac2vzd0yf28yre4m3w2lkcrmegjz6lu83lrl4zw7x2sgsds4g5hnc.json
Hello,
Here is the signature for this commit:
```
{
"message": "38353162346437653837666562613732666665383838643862316136663137396438363437643564",
"signature": "9f114ce44d049d275de7b1bdc295c2c7ee92fec3411ec96094ec8509fcc7781c7e8a084816107cc3e3e26ceddc52c60aa1a71f09e15a2f34af5e40f0fb729503",
"address": "erd1t8p8eac2vzd0yf28yre4m3w2lkcrmegjz6lu83lrl4zw7x2sgsds4g5hnc",
"version": 1,
"signer": "sdk-js"
}
```
Thanks !
> Add account erd1t8p8eac2vzd0yf28yre4m3w2lkcrmegjz6lu83lrl4zw7x2sgsds4g5hnc

- devnet/identities/ProjectX/info.json
Hi,
Sorry I messed up on my previous commit.
Here's a fixed version.
```
{
"message": "0x63333961663661623538363835363137303431373766353966656638376661353363653831386634",
"signature": "0xf94c12e84b7f9e83389e3d0a4f15d39bdf4ace8b9f6e0393be15495d83e8024d32db53c6ec27d9d97779c3062416f4b494fd37ba200d95a34f765f7c49eb470a",
"address": "erd14gna744kn8g8e0ganj94ddhwg3306mf634xgm54rrlmyhgwrvdlsh9u2px",
"version": 1,
"signer": "sdk-js"
}
```
Thanks!
> Update devnet identity for Project X provider

- accounts/erd1qqqqqqqqqqqqqpgqq33eh6y7h5x72dwskh6r5cajrp6pymnv899q20mft3.json
Last commit: f65971ad838fb7fa65546d60aff4e43cfb56bfd9
Sign: 
{
"message": "66363539373161643833386662376661363535343664363061666634653433636662353662666439",
"signature": "a8a1884f108d45c51e0c138e0f3f37ae1055058ef2789f956ba5d30bcc93ed5f0ffde415c6238b16c28cc37108147a749a76ecdbb1e198ce2c3c4b04c4a1a303",
"address": "erd1kfrxa85zsqharcg78n3tc90flh590x2lk4r65y8spr8gr0hr899qt4hs9v",
"version": 1,
"signer": "sdk-js"
}
> JSON for OOX NFT Staking

- accounts/erd1qqqqqqqqqqqqqpgqt4x2q3h4ya4q0wnf3ceayncgujav86a06avsvrlale.json
```
{
"message": "36323731666666336561363939363332653061326663363430326334666330353437623631356630",
"signature": "b041ee430452320b0da80eecc7f840010511139573a470b5016c9691952dfe60026a1f0f5e4bcfb4f2778e66e5286f044843cbe47957da94e1712f7a29b9780c",
"version": 1,
}
```
> JEX: add JEX-BTC LP account
